/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.myco.ladybird.common.exchange.endpoint;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class ExchangeRequestPayload extends org.apache.thrift.TUnion<ExchangeRequestPayload, ExchangeRequestPayload._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ExchangeRequestPayload");
  private static final org.apache.thrift.protocol.TField CREATE_ACCOUNT_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("createAccountRequest", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CONNECT_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("connectRequest", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField PING_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("pingRequest", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CREATE_ACCOUNT_REQUEST((short)1, "createAccountRequest"),
    CONNECT_REQUEST((short)2, "connectRequest"),
    PING_REQUEST((short)3, "pingRequest");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CREATE_ACCOUNT_REQUEST
          return CREATE_ACCOUNT_REQUEST;
        case 2: // CONNECT_REQUEST
          return CONNECT_REQUEST;
        case 3: // PING_REQUEST
          return PING_REQUEST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CREATE_ACCOUNT_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("createAccountRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CreateAccountRequest.class)));
    tmpMap.put(_Fields.CONNECT_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("connectRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ConnectRequest.class)));
    tmpMap.put(_Fields.PING_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("pingRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PingRequest.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExchangeRequestPayload.class, metaDataMap);
  }

  public ExchangeRequestPayload() {
    super();
  }

  public ExchangeRequestPayload(_Fields setField, Object value) {
    super(setField, value);
  }

  public ExchangeRequestPayload(ExchangeRequestPayload other) {
    super(other);
  }
  public ExchangeRequestPayload deepCopy() {
    return new ExchangeRequestPayload(this);
  }

  public static ExchangeRequestPayload createAccountRequest(CreateAccountRequest value) {
    ExchangeRequestPayload x = new ExchangeRequestPayload();
    x.setCreateAccountRequest(value);
    return x;
  }

  public static ExchangeRequestPayload connectRequest(ConnectRequest value) {
    ExchangeRequestPayload x = new ExchangeRequestPayload();
    x.setConnectRequest(value);
    return x;
  }

  public static ExchangeRequestPayload pingRequest(PingRequest value) {
    ExchangeRequestPayload x = new ExchangeRequestPayload();
    x.setPingRequest(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CREATE_ACCOUNT_REQUEST:
        if (value instanceof CreateAccountRequest) {
          break;
        }
        throw new ClassCastException("Was expecting value of type CreateAccountRequest for field 'createAccountRequest', but got " + value.getClass().getSimpleName());
      case CONNECT_REQUEST:
        if (value instanceof ConnectRequest) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ConnectRequest for field 'connectRequest', but got " + value.getClass().getSimpleName());
      case PING_REQUEST:
        if (value instanceof PingRequest) {
          break;
        }
        throw new ClassCastException("Was expecting value of type PingRequest for field 'pingRequest', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CREATE_ACCOUNT_REQUEST:
          if (field.type == CREATE_ACCOUNT_REQUEST_FIELD_DESC.type) {
            CreateAccountRequest createAccountRequest;
            createAccountRequest = new CreateAccountRequest();
            createAccountRequest.read(iprot);
            return createAccountRequest;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case CONNECT_REQUEST:
          if (field.type == CONNECT_REQUEST_FIELD_DESC.type) {
            ConnectRequest connectRequest;
            connectRequest = new ConnectRequest();
            connectRequest.read(iprot);
            return connectRequest;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PING_REQUEST:
          if (field.type == PING_REQUEST_FIELD_DESC.type) {
            PingRequest pingRequest;
            pingRequest = new PingRequest();
            pingRequest.read(iprot);
            return pingRequest;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CREATE_ACCOUNT_REQUEST:
        CreateAccountRequest createAccountRequest = (CreateAccountRequest)value_;
        createAccountRequest.write(oprot);
        return;
      case CONNECT_REQUEST:
        ConnectRequest connectRequest = (ConnectRequest)value_;
        connectRequest.write(oprot);
        return;
      case PING_REQUEST:
        PingRequest pingRequest = (PingRequest)value_;
        pingRequest.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CREATE_ACCOUNT_REQUEST:
          CreateAccountRequest createAccountRequest;
          createAccountRequest = new CreateAccountRequest();
          createAccountRequest.read(iprot);
          return createAccountRequest;
        case CONNECT_REQUEST:
          ConnectRequest connectRequest;
          connectRequest = new ConnectRequest();
          connectRequest.read(iprot);
          return connectRequest;
        case PING_REQUEST:
          PingRequest pingRequest;
          pingRequest = new PingRequest();
          pingRequest.read(iprot);
          return pingRequest;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CREATE_ACCOUNT_REQUEST:
        CreateAccountRequest createAccountRequest = (CreateAccountRequest)value_;
        createAccountRequest.write(oprot);
        return;
      case CONNECT_REQUEST:
        ConnectRequest connectRequest = (ConnectRequest)value_;
        connectRequest.write(oprot);
        return;
      case PING_REQUEST:
        PingRequest pingRequest = (PingRequest)value_;
        pingRequest.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CREATE_ACCOUNT_REQUEST:
        return CREATE_ACCOUNT_REQUEST_FIELD_DESC;
      case CONNECT_REQUEST:
        return CONNECT_REQUEST_FIELD_DESC;
      case PING_REQUEST:
        return PING_REQUEST_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public CreateAccountRequest getCreateAccountRequest() {
    if (getSetField() == _Fields.CREATE_ACCOUNT_REQUEST) {
      return (CreateAccountRequest)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'createAccountRequest' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setCreateAccountRequest(CreateAccountRequest value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CREATE_ACCOUNT_REQUEST;
    value_ = value;
  }

  public ConnectRequest getConnectRequest() {
    if (getSetField() == _Fields.CONNECT_REQUEST) {
      return (ConnectRequest)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'connectRequest' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setConnectRequest(ConnectRequest value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CONNECT_REQUEST;
    value_ = value;
  }

  public PingRequest getPingRequest() {
    if (getSetField() == _Fields.PING_REQUEST) {
      return (PingRequest)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'pingRequest' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setPingRequest(PingRequest value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PING_REQUEST;
    value_ = value;
  }

  public boolean isSetCreateAccountRequest() {
    return setField_ == _Fields.CREATE_ACCOUNT_REQUEST;
  }


  public boolean isSetConnectRequest() {
    return setField_ == _Fields.CONNECT_REQUEST;
  }


  public boolean isSetPingRequest() {
    return setField_ == _Fields.PING_REQUEST;
  }


  public boolean equals(Object other) {
    if (other instanceof ExchangeRequestPayload) {
      return equals((ExchangeRequestPayload)other);
    } else {
      return false;
    }
  }

  public boolean equals(ExchangeRequestPayload other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(ExchangeRequestPayload other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
