/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.myco.ladybird.common.exchange.endpoint;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class ExchangeResponsePayload extends org.apache.thrift.TUnion<ExchangeResponsePayload, ExchangeResponsePayload._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ExchangeResponsePayload");
  private static final org.apache.thrift.protocol.TField CREATE_ACCOUNT_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("createAccountResponse", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CONNECT_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("connectResponse", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField PING_RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("pingResponse", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CREATE_ACCOUNT_RESPONSE((short)1, "createAccountResponse"),
    CONNECT_RESPONSE((short)2, "connectResponse"),
    PING_RESPONSE((short)3, "pingResponse");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CREATE_ACCOUNT_RESPONSE
          return CREATE_ACCOUNT_RESPONSE;
        case 2: // CONNECT_RESPONSE
          return CONNECT_RESPONSE;
        case 3: // PING_RESPONSE
          return PING_RESPONSE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CREATE_ACCOUNT_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("createAccountResponse", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CreateAccountResponse.class)));
    tmpMap.put(_Fields.CONNECT_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("connectResponse", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ConnectResponse.class)));
    tmpMap.put(_Fields.PING_RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("pingResponse", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PingResponse.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExchangeResponsePayload.class, metaDataMap);
  }

  public ExchangeResponsePayload() {
    super();
  }

  public ExchangeResponsePayload(_Fields setField, Object value) {
    super(setField, value);
  }

  public ExchangeResponsePayload(ExchangeResponsePayload other) {
    super(other);
  }
  public ExchangeResponsePayload deepCopy() {
    return new ExchangeResponsePayload(this);
  }

  public static ExchangeResponsePayload createAccountResponse(CreateAccountResponse value) {
    ExchangeResponsePayload x = new ExchangeResponsePayload();
    x.setCreateAccountResponse(value);
    return x;
  }

  public static ExchangeResponsePayload connectResponse(ConnectResponse value) {
    ExchangeResponsePayload x = new ExchangeResponsePayload();
    x.setConnectResponse(value);
    return x;
  }

  public static ExchangeResponsePayload pingResponse(PingResponse value) {
    ExchangeResponsePayload x = new ExchangeResponsePayload();
    x.setPingResponse(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case CREATE_ACCOUNT_RESPONSE:
        if (value instanceof CreateAccountResponse) {
          break;
        }
        throw new ClassCastException("Was expecting value of type CreateAccountResponse for field 'createAccountResponse', but got " + value.getClass().getSimpleName());
      case CONNECT_RESPONSE:
        if (value instanceof ConnectResponse) {
          break;
        }
        throw new ClassCastException("Was expecting value of type ConnectResponse for field 'connectResponse', but got " + value.getClass().getSimpleName());
      case PING_RESPONSE:
        if (value instanceof PingResponse) {
          break;
        }
        throw new ClassCastException("Was expecting value of type PingResponse for field 'pingResponse', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case CREATE_ACCOUNT_RESPONSE:
          if (field.type == CREATE_ACCOUNT_RESPONSE_FIELD_DESC.type) {
            CreateAccountResponse createAccountResponse;
            createAccountResponse = new CreateAccountResponse();
            createAccountResponse.read(iprot);
            return createAccountResponse;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case CONNECT_RESPONSE:
          if (field.type == CONNECT_RESPONSE_FIELD_DESC.type) {
            ConnectResponse connectResponse;
            connectResponse = new ConnectResponse();
            connectResponse.read(iprot);
            return connectResponse;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case PING_RESPONSE:
          if (field.type == PING_RESPONSE_FIELD_DESC.type) {
            PingResponse pingResponse;
            pingResponse = new PingResponse();
            pingResponse.read(iprot);
            return pingResponse;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CREATE_ACCOUNT_RESPONSE:
        CreateAccountResponse createAccountResponse = (CreateAccountResponse)value_;
        createAccountResponse.write(oprot);
        return;
      case CONNECT_RESPONSE:
        ConnectResponse connectResponse = (ConnectResponse)value_;
        connectResponse.write(oprot);
        return;
      case PING_RESPONSE:
        PingResponse pingResponse = (PingResponse)value_;
        pingResponse.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case CREATE_ACCOUNT_RESPONSE:
          CreateAccountResponse createAccountResponse;
          createAccountResponse = new CreateAccountResponse();
          createAccountResponse.read(iprot);
          return createAccountResponse;
        case CONNECT_RESPONSE:
          ConnectResponse connectResponse;
          connectResponse = new ConnectResponse();
          connectResponse.read(iprot);
          return connectResponse;
        case PING_RESPONSE:
          PingResponse pingResponse;
          pingResponse = new PingResponse();
          pingResponse.read(iprot);
          return pingResponse;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case CREATE_ACCOUNT_RESPONSE:
        CreateAccountResponse createAccountResponse = (CreateAccountResponse)value_;
        createAccountResponse.write(oprot);
        return;
      case CONNECT_RESPONSE:
        ConnectResponse connectResponse = (ConnectResponse)value_;
        connectResponse.write(oprot);
        return;
      case PING_RESPONSE:
        PingResponse pingResponse = (PingResponse)value_;
        pingResponse.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case CREATE_ACCOUNT_RESPONSE:
        return CREATE_ACCOUNT_RESPONSE_FIELD_DESC;
      case CONNECT_RESPONSE:
        return CONNECT_RESPONSE_FIELD_DESC;
      case PING_RESPONSE:
        return PING_RESPONSE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public CreateAccountResponse getCreateAccountResponse() {
    if (getSetField() == _Fields.CREATE_ACCOUNT_RESPONSE) {
      return (CreateAccountResponse)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'createAccountResponse' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setCreateAccountResponse(CreateAccountResponse value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CREATE_ACCOUNT_RESPONSE;
    value_ = value;
  }

  public ConnectResponse getConnectResponse() {
    if (getSetField() == _Fields.CONNECT_RESPONSE) {
      return (ConnectResponse)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'connectResponse' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setConnectResponse(ConnectResponse value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.CONNECT_RESPONSE;
    value_ = value;
  }

  public PingResponse getPingResponse() {
    if (getSetField() == _Fields.PING_RESPONSE) {
      return (PingResponse)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'pingResponse' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setPingResponse(PingResponse value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.PING_RESPONSE;
    value_ = value;
  }

  public boolean isSetCreateAccountResponse() {
    return setField_ == _Fields.CREATE_ACCOUNT_RESPONSE;
  }


  public boolean isSetConnectResponse() {
    return setField_ == _Fields.CONNECT_RESPONSE;
  }


  public boolean isSetPingResponse() {
    return setField_ == _Fields.PING_RESPONSE;
  }


  public boolean equals(Object other) {
    if (other instanceof ExchangeResponsePayload) {
      return equals((ExchangeResponsePayload)other);
    } else {
      return false;
    }
  }

  public boolean equals(ExchangeResponsePayload other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(ExchangeResponsePayload other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
